import "./globals.css";
import { GeistSans, GeistMono } from "geist/font"; // ✅ correct import
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header"; 
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "AI based Education System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="min-h-screen pt-16">{children}</main>
          <Toaster richColors/>
          <footer className="bg-muted/50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p>Made by Prerna Arora</p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
