import "./globals.css";
import { GeistSans, GeistMono } from "geist/font"; // ✅ correct import
import { ThemeProvider } from "@/components/theme-provider";
import SiteChrome from "@/components/site-chrome";
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "AI based Education System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          forcedTheme="dark"
          disableTransitionOnChange
        >
          <SiteChrome>{children}</SiteChrome>
          <Toaster richColors/>
        </ThemeProvider>
      </body>
    </html>
  );
}
